# Generated by Django 3.1.7 on 2024-09-15 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SPMT', '0002_auto_20240914_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsubmission',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='professor',
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='matriculation_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='student_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='subject_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='file',
            field=models.FileField(upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='SPMT.customuser'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
