# Generated by Django 3.1.7 on 2024-09-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPMT', '0005_auto_20240919_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='submitted_to',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
