# Generated by Django 3.1.7 on 2024-09-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPMT', '0006_auto_20240919_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
