# Generated by Django 3.1.7 on 2024-09-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPMT', '0007_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='student_name',
        ),
    ]
