# Generated by Django 3.1.7 on 2024-09-19 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SPMT', '0008_remove_projectsubmission_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='student_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
